AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: GET

    GetCategoriesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: category.handler
      Runtime: nodejs6.10
      CodeUri: ./
      Events:
        CategoriesApi:
          Type: Api
          Properties:
            Path: /categories
            Method: GET

    
    GetMoviesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: movies.handler
      Runtime: nodejs8.10
      CodeUri: ./
      Events:
        MoviesApi:
          Type: Api
          Properties:
            Path: /movies
            Method: GET